version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: adapp-mysql
    restart: unless-stopped
    env_file:
      - ./apps/server/.env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 