FROM mysql:latest

# Set environment variables for MySQL
ARG MYSQL_DATABASE=adapp
ARG MYSQL_USER=adappuser
ARG MYSQL_PASSWORD=adapppass
ARG MYSQL_ROOT_PASSWORD=rootpass

ENV MYSQL_DATABASE=${MYSQL_DATABASE}
ENV MYSQL_USER=${MYSQL_USER}
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}
ENV MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

EXPOSE 3306 